### ISSUE TITLE
Exception: Sheetname 'RET', with case ignored, is already in use.

### ISSUE THREAD

**Issue by TPIMarienburg** [TransitionProjects/ServicesConsistencyReport#1]
'\\tproserver\IT\Reporting Programs\ServicesConsistancyReport'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
Traceback (most recent call last):
  File "\\tproserver\IT\Reporting Programs\ServicesConsistancyReport\ConsistancyCheck.py", line 126, in <module>
    a.process()
  File "\\tproserver\IT\Reporting Programs\ServicesConsistancyReport\ConsistancyCheck.py", line 107, in process
    self.save_values(data)
  File "\\tproserver\IT\Reporting Programs\ServicesConsistancyReport\ConsistancyCheck.py", line 118, in save_values
    dept_df.to_excel(writer, str(dept_name)[:5], engine="xlsxwriter", index=False)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py", line 1545, in to_excel
    engine=engine)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\formats\excel.py", line 649, in write
    freeze_panes=freeze_panes)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\excel.py", line 1612, in write_cells
    wks = self.book.add_worksheet(sheet_name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\xlsxwriter\workbook.py", line 178, in add_worksheet
    return self._add_sheet(name, worksheet_class=worksheet_class)
  File "C:\ProgramData\Anaconda3\lib\site-packages\xlsxwriter\workbook.py", line 664, in _add_sheet
    name = self._check_sheetname(name, isinstance(worksheet, Chartsheet))
  File "C:\ProgramData\Anaconda3\lib\site-packages\xlsxwriter\workbook.py", line 731, in _check_sheetname
    sheetname)
Exception: Sheetname 'RET', with case ignored, is already in use.
[Finished in 321.29s]

**Comment by TPIMarienburg** [comment]
This was a problem with the "Staff List" file having the Dept. retention shortened to both "RET" and "Ret"
